DROP TABLE IF EXISTS daily_platform_metrics;
DROP TABLE IF EXISTS daily_event_metrics;
DROP TABLE IF EXISTS settlements;
DROP TABLE IF EXISTS payouts;
DROP TABLE IF EXISTS ledger_entries;
DROP TABLE IF EXISTS finance_settings;
DROP TABLE IF EXISTS user_event_interactions;
DROP TABLE IF EXISTS campaign_sends;
DROP TABLE IF EXISTS campaigns;
ALTER TABLE events DROP COLUMN IF EXISTS featured_until;
ALTER TABLE events DROP COLUMN IF EXISTS featured;
DROP TABLE IF EXISTS event_announcements;
ALTER TABLE orders DROP COLUMN IF EXISTS refund_amount_cents;
DROP TABLE IF EXISTS event_reviews;
DROP TABLE IF EXISTS refund_requests;
ALTER TABLE users DROP COLUMN IF EXISTS deleted_reason;
ALTER TABLE users DROP COLUMN IF EXISTS deleted_at;
DROP TABLE IF EXISTS support_messages;
DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS saved_payment_methods;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS notification_preferences;
DROP TABLE IF EXISTS user_profiles;
